project_id = "zupnvqiplubxsubvsxzc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[functions.join-game]
verify_jwt = false

[functions.validate-player]
verify_jwt = false

[functions.player-heartbeat]
verify_jwt = false

[functions.reset-player-token]
verify_jwt = false

[functions.create-test-admin]
verify_jwt = false

[functions.kick-player]
verify_jwt = false

[functions.start-game]
verify_jwt = false

[functions.manage-phase]
verify_jwt = false

[functions.publish-event]
verify_jwt = false

[functions.close-phase1-bets]
verify_jwt = false

[functions.publish-positions]
verify_jwt = false

[functions.resolve-combat]
verify_jwt = false
